export const formRequestButton = [
  {
    key: 'register',
    name: 'register',
    text: 'Register',
    htmlType: 'submit',
    type: 'primary',
    idForm: 'myForm',
    loading: 'loadingRegister',
  },
  {
    key: 'update',
    name: 'update',
    text: 'Update',
    htmlType: 'submit',
    type: 'primary',
    idForm: 'myForm',
    loading: 'loadingUpdate',
  },
  {
    key: 'cancel',
    name: 'cancel',
    text: 'Cancel',
    htmlType: '',
    type: '',
    idForm: '',
  },
  {
    key: 'delete',
    name: 'delete',
    text: 'Delete',
    htmlType: 'submit',
    type: 'primary',
    idForm: 'myForm',
    loading: 'loadingDelete',
    danger: 'danger',
  },
]
